# Use an official lightweight Node image as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Salin sumber daya proyek ReactJS
COPY . .

# Install app dependencies (only production dependencies)
RUN npm install

RUN npm run build

RUN npm install -g serve

# Expose port 80 to the outside world
EXPOSE 3000

# Command to run the app in production
CMD ["serve", "-s", "build"]
